# Generated by Django 4.1.7 on 2023-03-29 14:21

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FeedbackModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        default=None,
                        help_text="Your email will help use to reach you when we launch a new version of the application",
                        max_length=254,
                        verbose_name="Email Address",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default=None,
                        help_text="This is how we will address you in the name",
                        max_length=128,
                        verbose_name="Full Name",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        default=None,
                        help_text="Provide the feedback here",
                        verbose_name="Message",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
            ],
            options={
                "verbose_name": "Feedback Submission",
                "verbose_name_plural": "Feedback Submissions",
                "get_latest_by": "-created_at",
            },
        ),
    ]
