# Generated by Django 4.1.7 on 2023-03-29 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feedback", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedbackmodel",
            name="name",
            field=models.CharField(
                default=None,
                help_text="This is how we will address you in the email",
                max_length=128,
                verbose_name="Full Name",
            ),
        ),
    ]
